apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jo1bk1l7d-go
  janus-idp.io/tekton: jo1bk1l7d-go
  backstage.io/kubernetes-id: jo1bk1l7d-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jo1bk1l7d-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
