apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jo1bk1l7d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jo1bk1l7d-go 
  name: jo1bk1l7d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jo1bk1l7d-go 
